### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by ZabegaevN**

### CODE REVIEW

**Comment by kostua16** [comment]
Build successfully completed for commit 39a7e55317ef96dcc826dd846adbea1af53b80a1

**Comment by kostua16** [comment]
Build successfully completed for commit 39a7e55317ef96dcc826dd846adbea1af53b80a1

**Comment by kostua16** [comment]
Depends on #347 due to build failure for commit 1dab56d31f8dbf259775795ccb7faba6b77fe341

**Comment by kostua16** [comment]
Depends on #349 due to build failure for commit c7adf0acf0194874c7bf253fc7281383a6438f75

**Comment by kostua16** [comment]
Depends on #350 due to build failure for commit 7bc9f2233778d04a55587b4c944a5feabb892d87

**Comment by Spec163** [comment]
осталось сделать валидацию для формы регистрации

**Comment by kostua16** [comment]
Build successfully completed for commit 38d1d2edc1fe70f6b8f241528c7acdc13b189a2c

**Comment by kostua16** [comment]
Build successfully completed for commit 263817af4fe57fb9303487884250b686636f8511

**Comment by kostua16** [comment]
Build successfully completed for commit 9bf4641f6b1dd5a1941d0c6d2886c52ecddf49f3

**Comment by kostua16** [comment]
Build successfully completed for commit 9575e373d4782d426dd87a188e70e8b5ee51030f

**Comment by kostua16** [comment]
Build successfully completed for commit ea51ec30d75e1950d3b6ef5671a2111dacee8466

**Comment by kostua16** [comment]
Build successfully completed for commit 8904ccc5cef8cb73dbaacf8cdb6cee4cc9cb94ad

**Comment by kostua16** [comment]
Build successfully completed for commit 8904ccc5cef8cb73dbaacf8cdb6cee4cc9cb94ad

**Comment by kostua16** [comment]
Build successfully completed for commit 1a741807d3b26b24bc620fdeaa6ff49065eb2e38

**Comment by kostua16** [comment]
Build successfully completed for commit f6b1b77c6af24df648e1776151ba807bfd402dca

**Comment by kostua16** [comment]
Build successfully completed for commit d51ddd4839b5d0fd70f25c076c5bdf5286be138e

**Comment by kostua16** [comment]
Build successfully completed for commit 774423729baa1cce09e5e25e14b109dca58c34bf

**Comment by kostua16** [comment]
Depends on #358 due to build failure for commit 8c066ac63d7964591974755b0fdaf18267c745ee

**Comment by kostua16** [comment]
Depends on #360 due to build failure for commit b64dd3f3bb5c8335fcb0c0593da93b9168078183

**Comment by kostua16** [comment]
Depends on #362 due to build failure for commit a755e474ef755083984f6e0e45a0ef3b819d1335

**Comment by kostua16** [comment]
Build successfully completed for commit 85f7202c98a9443cbae96fc5f33fd711c14615df

**Review by kostua16 — APPROVED** [review]

**Pull request merged**
