### PR TITLE
Настройка фронтенд-сервара для деплоя

### PR DESCRIPTION
**Pull request by Spec163**

### CODE REVIEW

**Comment by kostua16** [comment]
Build successfully completed for commit cff311c113a1fec59abb02baad83a60bb8fa1875

**Comment by kostua16** [comment]
Build successfully completed for commit b1ff7f30c8e4124a7a9b7415f26742abfd12ebe5

**Comment by kostua16** [comment]
Build successfully completed for commit e953b14deb6e0424461d28dcedd62442200ccaa8

**Comment by Spec163** [comment]
Нужно подредачить Procfile и добавить скрипт

**Comment by kostua16** [comment]
Build successfully completed for commit 7f0847214bb339b97756c6f434791fd7aad3e17e

**Comment by kostua16** [comment]
Build successfully completed for commit 9bc90ec41480aa894251c9f99e2fc5b07f82666f

**Review by kostua16 — APPROVED** [review]

**Pull request merged**
