### PR TITLE
WIP Доработка бекенда: Изменение способа отлова ошибок

### PR DESCRIPTION
**Pull request by Spec163**
Completed Large [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=kostua16&utm_campaign=badge_info)

Первые два коммита не смотрите, я кривое сообщение написал, пришлось переименовывать.

### CODE REVIEW

**Comment by kostua16** [comment]
Build successfully completed for commit e1c538c27f6f264e2df9d676dd6a5d49c9906d25

**Comment by kostua16** [comment]
Build successfully completed for commit e1c538c27f6f264e2df9d676dd6a5d49c9906d25

**Comment by kostua16** [comment]
Build successfully completed for commit e1c538c27f6f264e2df9d676dd6a5d49c9906d25

**Comment by Spec163** [comment]
Что-то рестайлер в clang-format делает только хуже, или мне кажется?

**Comment by kostua16** [comment]
Build successfully completed for commit e1c538c27f6f264e2df9d676dd6a5d49c9906d25

**Comment by kostua16** [comment]
Build successfully completed for commit e1c538c27f6f264e2df9d676dd6a5d49c9906d25

**Comment by kostua16** [comment]
Build successfully completed for commit e1c538c27f6f264e2df9d676dd6a5d49c9906d25

**Comment by kostua16** [comment]
Build successfully completed for commit 4e15112faf810f335a66cd3ff241cbe982d869d9

**Comment by kostua16** [comment]
Depends on #116 due to build failure for commit cf47f547cb6b511242f463e7cc874d4e4147d672

**Comment by kostua16** [comment]
Build successfully completed for commit 03ea24bf2389fb6b634df9d42c30b6f7e12a8785

**Comment by kostua16** [comment]
Build successfully completed for commit a13b6306b6180555fae5e4a992f40239f455aea2

**Comment by kostua16** [comment]
Depends on #156 due to build failure for commit d956a40c54a30bd8aa842aba39edf4d90be81400

**Comment by kostua16** [comment]
Build successfully completed for commit 7e619166c472d508ad1d49ce63b4c820bf09c6ee

**Comment by kostua16** [comment]
Build successfully completed for commit 7e619166c472d508ad1d49ce63b4c820bf09c6ee

**Comment by kostua16** [comment]
Build successfully completed for commit 267583cf990871bf05f19c21d81ac78114691ab0

**Comment by kostua16** [comment]
Depends on #173 due to build failure for commit 9d4255647b77629bea7d4a06c76b77c0dc7f3bba

**Comment by kostua16** [comment]
Depends on #175 due to build failure for commit 9d4255647b77629bea7d4a06c76b77c0dc7f3bba

**Pull request closed without merging**
